name: login_demo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter_riverpod: ^2.4.9

dev_dependencies:
  intl_utils: ^2.8.13
  flutter_test:
    sdk: flutter
